channels:
- conda-forge
dependencies:
- nbsphinx
- sphinx
- ase
- defusedxml
- future
- h5py
- matplotlib-base
- mendeleev
- numpy
- pandas
- phonopy
- pyiron_base
- pyscal
- scipy
- seekpath
- scikit-learn
- spglib
- structuretoolkit